package com.uhc.ubh.arithmatic.calculation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ArithmaticCalculationServicePort", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/")
@XmlSeeAlso({ ObjectFactory.class })
public interface ArithmaticCalculationServicePort {

    /**
     * 
     * @param in0
     * @param in1
     * @return returns int
     */
    @WebMethod(action = "http://arithmatic.ubh.uhc.com/calculation/sum")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "sum", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.SumResponse")
    public int sum(@WebParam(name = "in0", targetNamespace = "") int in0,
            @WebParam(name = "in1", targetNamespace = "") int in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return returns int
     */
    @WebMethod(action = "http://arithmatic.ubh.uhc.com/calculation/sub")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.SubResponse")
    public int sub(@WebParam(name = "in0", targetNamespace = "") int in0,
            @WebParam(name = "in1", targetNamespace = "") int in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return returns int
     */
    @WebMethod(action = "http://arithmatic.ubh.uhc.com/calculation/multiply")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.MultiplyResponse")
    public int multiply(@WebParam(name = "in0", targetNamespace = "") int in0,
            @WebParam(name = "in1", targetNamespace = "") int in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return returns int
     */
    @WebMethod(action = "http://arithmatic.ubh.uhc.com/calculation/division")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", className = "com.uhc.ubh.arithmatic.calculation.DivisionResponse")
    public int division(@WebParam(name = "in0", targetNamespace = "") int in0,
            @WebParam(name = "in1", targetNamespace = "") int in1);

}
