package com.uhc.ubh.arithmatic.calculation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ArithmaticCalculationService", targetNamespace = "http://arithmatic.ubh.uhc.com/calculation/", wsdlLocation = "http://localhost:8090/MathsCalculator/1.0.wsdl")
public class ArithmaticCalculationService extends Service {

    private final static URL ARITHMATICCALCULATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ARITHMATICCALCULATIONSERVICE_EXCEPTION;
    private final static QName ARITHMATICCALCULATIONSERVICE_QNAME = new QName(
            "http://arithmatic.ubh.uhc.com/calculation/", "ArithmaticCalculationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/MathsCalculator/1.0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ARITHMATICCALCULATIONSERVICE_WSDL_LOCATION = url;
        ARITHMATICCALCULATIONSERVICE_EXCEPTION = e;
    }

    public ArithmaticCalculationService() {
        super(__getWsdlLocation(), ARITHMATICCALCULATIONSERVICE_QNAME);
    }

    public ArithmaticCalculationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ARITHMATICCALCULATIONSERVICE_QNAME, features);
    }

    public ArithmaticCalculationService(URL wsdlLocation) {
        super(wsdlLocation, ARITHMATICCALCULATIONSERVICE_QNAME);
    }

    public ArithmaticCalculationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ARITHMATICCALCULATIONSERVICE_QNAME, features);
    }

    public ArithmaticCalculationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArithmaticCalculationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return returns ArithmaticCalculationServicePort
     */
    @WebEndpoint(name = "ArithmaticCalculationServicePort")
    public ArithmaticCalculationServicePort getArithmaticCalculationServicePort() {
        return super.getPort(
                new QName("http://arithmatic.ubh.uhc.com/calculation/", "ArithmaticCalculationServicePort"),
                ArithmaticCalculationServicePort.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns ArithmaticCalculationServicePort
     */
    @WebEndpoint(name = "ArithmaticCalculationServicePort")
    public ArithmaticCalculationServicePort getArithmaticCalculationServicePort(WebServiceFeature... features) {
        return super.getPort(
                new QName("http://arithmatic.ubh.uhc.com/calculation/", "ArithmaticCalculationServicePort"),
                ArithmaticCalculationServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ARITHMATICCALCULATIONSERVICE_EXCEPTION != null) {
            throw ARITHMATICCALCULATIONSERVICE_EXCEPTION;
        }
        return ARITHMATICCALCULATIONSERVICE_WSDL_LOCATION;
    }

}
